language: python
python:
    - '3.4'
    - '3.5'
    - '3.6'
    - pypy3
sudo: true
before_script:
    - PYTHON_BIN=python3 PIP_BIN=pip3 make install_dependencies build install_as_package clean

script:
    # execute unit tests to check inner logic
    #- make test

    # setup test SSH server for integration tests
    - PYTHON_BIN=python3 make setup_test_docker_host

    # build expectation
    - PYTHON_BIN=python3 make dev_build_expectations

    - make dev_http_run &
    - sleep 10 && killall python

    # print version number, if the tagged version is properly detected
    - python3 setup.py --version

deploy:
    skip_cleanup: true
    provider: pypi
    distributions: sdist bdist_wheel
    on:
        tags: true
        branch:
            - master
            - "/v?(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$/"
    user: marek_man
    password:
        secure: DFh8nCM9z5gjWyFyW0z7OVQg1FN6SWmCAlCjcN30ylBn1olIMzJXugItW6Wc8v1n1ZnhR0d1yd6MlL3Hzpu+iWHO1aZQADyeZfk3iAwIt6PGR/AkoboSBXPHmw1/a3bimrqbbzO0dVAmi+cgBqYRPQTDt1rz09BMUx2TzXvxSUdLi28L/RIY6sQ/0mYaTx1yLJNEa3FpNuMyL+77bDbH7W8q6W4lRkncCJU3BirSR/V5gpAIjYQ4RCZdZjbySNLvXG2RgFEG2M4b1bp7S6hVHK2hBr4z7RKj4QIXc1u7yTXG2m2UXgLfEAq9E4RIkTANaH0SnyzRIrXvsLnswiCUpfMv25mMioP5Ldtc52CVq6WDjTbAprwTQ6NYd8y6ffahYD8HSyge6gC6j3JiyC7/Kz/weir6Em5zqwUc61l/tgf2LWczhZ9UUPOtE3euZpyc//RfOEjpIt7xDE5i7hqvKnJ6x5h8lowpmdbNh8y7K91cy+3B73HwBdUPpqf1jV6xJZ/zDofR0DBe8VgXxd4FbVaElvoBOVScqIlbz4EAJJt77/KKThpHBeZg72ZUD9MstUSrPV4Lbxbp4vhr+IIQt2jGFrpDDEsizELSzjCsaqBwUCwF8FfxbR6irjuofehrxwu5MqxSItLl5gILvnfcKoQpsl9Sgt0ciuPQw6o1w1Q=
